C **********************************************************************
C     
      SUBROUTINE CHINITAER
C     
      include  'com_aerg.h'
      include  'com_aers.h'
      include  'com_aerd.h'
      include  'com_aera.h'
      PARAMETER (IFSSP=NFSP+1,ILSSP=NFSP+NRSP)
C     
      LOGICAL LTDBC, LTDFL, LSEASBC, LINTP
C     DIURNAL PRINTOUTS REQUESTED IN FASTCH
      LOGICAL DOUTFS, NOUTFS, NOUTSS, FOUT, DIURNL
C     WALL: LAT, LEV  RANGES; START & END DAYS;
      INTEGER IWALL1, IWALL2, JWALL1, JWALL2, IWALD1, IWALD2, 
     *    JWALR1, JWALR2
C     LWALL=.TRUE. if any slow species has wall conditions
C     LHSCT=.TRUE. to include subsonic or supersonic aircraft emissions
C     LTDIST=.TRUE. to include temperature distribution
      LOGICAL LWALL,LHSCT,LAERO,LTDIST,LPSC,LCONV
      INTEGER SAVFSP(NFSP),SAVSSP(NSSP),SAVPLQ(NPLQ),
     .    SAVJR(NJR),SAVFLX(NRSP+3),SAVAER(NSIZE)
      INTEGER LOLA(50),PRTFSP(NFSP),PRTSSP(NSSP)
      INTEGER ISPCONV(NRSP)
C     
C     ALLFSP CONTAINS ALL 20 FAST SPECIES MIXING RATIOS
      DOUBLE PRECISION ALLFSP(NLT,NHT,NFSP)
C     ALLSSP CONTAINS 12 SPECIES MIXING RATIOS
      DOUBLE PRECISION ALLSSP(NLT,NHT,NSSP)
C     PHOTOCHEMICAL RATES:  PRODUCTION, LINEAR AND QUADRATIC LOSS
C     ALL IN ONE ARRAY FOR 12 SPECIES
      DOUBLE PRECISION ALLPLQ(NLT,NHT,NPLQ)
C     ALLJR CONTAINS J-RATES AT ALL SPATIAL POINTS
      DOUBLE PRECISION ALLJR(NLT,NHT,NJR)

      DOUBLE PRECISION RR,QJ,QTMP,QYIELD,QZ(NWLI,10),WBIN,WL,FLX,VAL
C     LOSS TERM POWER  FOR SPECIE NUMBER I
C     LTPW(I)=1 IF LINEAR
C     =2 IF QUADRATIC
      DIMENSION LTPW(NRSP)
      REAL KYSUMM,KZTROP,KZSTRA,MOLECWT,TMP1(NLT,NHT)
      INTEGER ITROP(NLT)
      LOGICAL DONE(NTSP)
C     MIXING RATIOS AT THE BOTTOM BOUNDARY OR
C     BOTTOM FLUX IN MOLECULES/CM**2/SEC
      REAL BBSP(NLT,NRSP),BBSPA(NTN,NLT,NRSP),BBDEP(NLT,NRSP),
     $     IDAYBB(NTN)
C     ARRAYS TO READ IN BOUNDARY CONDITIONS
      DIMENSION BC(24)
      LOGICAL SAVNOON,SAVDAY,SAVNIT,SAVAVG,SAVMID,SAVRIS,SAVSET,SAVALL
C     
      COMMON /CAPTN/ MODNO,NODAY,NSTOP,IYEAR,IDOFY
C       TIME STEP PARAMETERS READ FROM SETUP FILE
      COMMON /DEBUG/LOLA,PRTFSP,PRTSSP
      COMMON /SWITCH/SAVFSP,SAVSSP,SAVPLQ,SAVJR,SAVFLX,SAVAER
      COMMON /LOGIC/LTDBC,LTDFL,LSEASBC,LINTP,LHSCT,LAERO,LTDIST,LPSC,
     $     LCONV
C       MIXING RATIOS FOR ALL CALCULATED SPECIES
      COMMON /SPEC/ALLFSP,ALLSSP,ALLPLQ,ALLJR
C       SPECIES NAMES
      COMMON /SID/SPID(NTSP),PLQID(NPLQ)
C         INDICES OF SPECIES IN ALLSP ARRAY
C         COMMON BLOCK TO INTERFACE DIURNAL CHEMISTRY
      COMMON /DIPARM/MINLAT,MAXLAT,MINALT,MAXALT,
     *               DOUTFS,NOUTFS,NOUTSS,FOUT,DIURNL
      COMMON/KVAL/CYY,CYZ,CZZ,KYSUMM,KYHT,KZTROP,KZSTRA,KZIN
C         SLOW SPECIES LOSS TERM POWER, BOUNDARY CONDITIONS
      COMMON /TREAT/LTPW,INDBC
      COMMON /BOUND/BBSP,BBSPA,BBDEP,IDAYBB
      COMMON /AIR/TMP(NLT,NHT),PR(NLT,NHT),AIRVD(NLT,NHT)
      COMMON /TEMPDIST/TMPDIST(NDIST,NLT,NHT),TMPAV(NLT,NHT),TD(NDIST)
      COMMON /ALTITUDES/ZSTAR(NHT),ZALT(NLT,NHT),ALAT(NLT)
      COMMON /PSC/PSC1(NLT,NHT),SPSC1(NLT,NHT),VSED1(NLT,NHT1),
     $     PSC2(NLT,NHT),SPSC2(NLT,NHT),VSED2(NLT,NHT1)
      COMMON/DIUROUT/SAVNOON,SAVDAY,SAVNIT,SAVAVG,SAVMID,SAVRIS,SAVSET,
     $     SAVALL
      COMMON/QID/QID(NJR),JRID(NJR)
      COMMON/REAC/REID(NKR)
      COMMON /LLWALL/LWALL
      COMMON /IIWALL/IWALL1, IWALL2, JWALL1, JWALL2, IWALD1, IWALD2,
     * JWALR1, JWALR2
C       ISWALL: wall type by species
C       WALRES:  residu (mult.factor) of mixrat, used according to ISWALL
      COMMON /WALLR/ISWALL(NRSP),WALRES(NRSP)
      COMMON /HSCTPARM/EI(NPOL),POLID(NPOL),MOLECWT(NPOL),SZDIST(NSIZE)
      COMMON /ODP/NCL,NBR,NFL 
      COMMON /RATE/RR(NRP,NKR)
      COMMON /QJ/QJ(NWLI,3,NJR),QTMP(3,NJR),QYIELD(NJR)
      COMMON /CCWVL/ WBIN(NWLI+1),WL(NWLI),FLX(NWLI)
      COMMON /TROP/ITROPDAT(NLT,4),ITROPDAY(4),LAST
      COMMON /KYYDATA/IRDKYY,IRDKZZ,AKYY,AKYY1,AKZZ,AKZZ1
      COMMON /SAVSURF1/SURFACE1(NLT,NHT),LSTEPAE,MRECAE
      COMMON /CONVECTION/ISPCONV
C
C
      DATA SAVFSP/NFSP*0/,SAVSSP/NSSP*0/,SAVPLQ/NPLQ*0/,
     .    SAVJR/NJR*0/,SAVFLX/NRSP*0,0,0,0/,SAVAER/NSIZE*0/
      DATA LOLA/50*0/,PRTFSP/NFSP*0/,PRTSSP/NSSP*0/


cc         LPSC=.TRUE.
cc         LTDIST=.FALSE.


C         READ THE INITIAL GUESS FOR FAST SPECIES
c      CALL GETSSP(ALLFSP,SPID,DONE,NFSP,LASTFAST,'allfsp.b')
C         READ THE INITIAL MIXING RATIOS FOR SLOW SPECIES
c      CALL GETSSP(ALLSSP,SPID(IFSSP),DONE,NRSP,IDAY,'allssp.b')
C        CHECK TO SEE IF START DAY MATCHES NODAY FROM TAPE
c      IF(IDAY.NE.NODAY) THEN
c         WRITE(16,*) ' *** INPUT ERROR ===> NSTART.NE.NODAY in allssp.b'
c         STOP 'START DAY CONFLICT'
c      END IF
c      DO ISP=1,NRSP
c         IF(INDBC(ISP).EQ.0) THEN
c            DO I=1,NLT
c               DO J=1,NHT
c                  ALLSSP(I,J,ISP)=ALLSSP(I,J,ISP)*SCALE(ISP)
c               END DO
c            END DO
c         END IF
c      END DO
C
      RETURN
      END
