C-*-Fortran-*-  -  this is used for emacs/Fortran mode capability, or just do M-x fortran-mode
C
      REAL LWCR
      COMMON /RADCOM/  AS(45),LWCR(46),PL(45),PLE(46),DPL(45),
     1 HI(45),HIS,HIE(46),TL(45),TLE(46),TGJR,SHL(45),SHLE(46),SHG,
     2 CLOUD(49),SWALE(46),SWIL(45),AL(46),TAUL(46),RN(45),TN(45),
     3 SRS(45),STN(45),
     3 TCOND(45),TPENE(45),TLOWL,TMIDL,THIGH,SG,SP,RSURF,RCLOUD,JALB,
     4 RHOJR(45),FK(5),XK(5),NFK, MZRAD,tir
