      SUBROUTINE RADT

      include "com2d.h"
      include "comphot.h"

      SAVE

C     REDUCED FLUXES AT ALL 
C     WAVELENGTHS FOR ALTITUDE ZP WITHOUT RADIATIVE TRANSFER.
C
      LOGICAL LGRIDP

	DO 2000 IJ=1,L$

	CALL FILL(IJ,Z$)

C     CALCULATION WITHOUT RADIATIVE TRANSFER (BEER'S LAW).
C     LOOP OVER WAVELENGTHS.
      DO 300 JL=1,IL$

	DO 1000 IK=1,Z$

         FLUXMS=FLUXMULT(JL,IJ,IK)
         TAUZ=TAUMULT(JL,IJ,IK)
C OPTICAL DEPTH AND REDUCED FLUX COMPUTED IN MULTSC


C     HERE STORE THE REDUCED FLUX.
	F=FLUXMS

	IF(JL.EQ.19 .AND. F.GE.1.E-20)THEN
	   O2JINT(IJ,IK)=O2JINT(IJ,IK)
C SCALE J(O2) TO DIURNAL AVERAGE VALUES AT ABOUT 200 NM - 4/7/95
        ENDIF

	IF(JL.EQ.19 .AND. F.LT.1.E-20)THEN
	   O2JINT(IJ,IK)=0.0E0
C SCALE J(O2) TO DIURNAL AVERAGE VALUES AT ABOUT 200 NM - 4/7/95
        ENDIF

      IF(F.LT.1.e-20)F=0.
      RFLUX(JL,IJ,IK)=F

1000	CONTINUE

300	CONTINUE

2000	CONTINUE

      RETURN
      END
