C
C   routine to load diurnally averaged Js from the AER array, JAVAER(IUNJR=NJR=121+3,L$,Z$)  
C      into the GSFC array J(PH$,L$,Z$) (in COMMON, REAL*8)
C
C      and do the same for the diurnally varying Js:
C          JAER(IUNJR+3,IUNTIME,L$,Z$) -> JDC(PH$,18,L$,Z$)
C
C   NOTE: the extra Js seperate in the AER model (CH4), are in JAVAER(iunjr+1->iunjr+3)
C
C 
        SUBROUTINE UNJMAP(JAVAER, JAER, IUNJR, IUNTIME)


        include "com2d.h"


        INTEGER IUNJR, IUNTIME
        REAL*8 JAVAER(IUNJR+3,L$,Z$), JAER(IUNJR+3,IUNTIME,L$,Z$)


        SAVE

C                        ! Note: JO2 channels for O, O1D (GSFC J1, J46) are now SEPARATE
        DO 100 IK=1,Z$
        DO 100 IJ=1,L$
           J(1,ij,ik) = JAVAER(1,ij,ik) 
           J(2,ij,ik) = JAVAER(3,ij,ik) 
           J(3,ij,ik) = JAVAER(2,ij,ik) 
           J(4,ij,ik) = JAVAER(12,ij,ik) 
           J(5,ij,ik) = JAVAER(7,ij,ik) 
           J(6,ij,ik) = JAVAER(8,ij,ik) 
           J(7,ij,ik) = JAVAER(6,ij,ik) 
           J(8,ij,ik) = JAVAER(11,ij,ik) 
           J(9,ij,ik) = JAVAER(9,ij,ik) 
           J(10,ij,ik) = JAVAER(30,ij,ik) 
           J(11,ij,ik) = JAVAER(31,ij,ik) 
           J(12,ij,ik) = JAVAER(80,ij,ik) 
           J(13,ij,ik) = JAVAER(34,ij,ik) 
           J(14,ij,ik) = JAVAER(13,ij,ik) 
           J(15,ij,ik) = JAVAER(10,ij,ik) 
           J(16,ij,ik) = JAVAER(5,ij,ik) 
           J(17,ij,ik) = JAVAER(59,ij,ik) 
           J(18,ij,ik) = JAVAER(14,ij,ik) 
           J(19,ij,ik) = JAVAER(18,ij,ik) 
           J(20,ij,ik) = JAVAER(19,ij,ik) 
           J(21,ij,ik) = JAVAER(16,ij,ik) 
           J(22,ij,ik) = JAVAER(17,ij,ik) 
           J(23,ij,ik) = JAVAER(15,ij,ik) 
           J(24,ij,ik) = JAVAER(33,ij,ik) 
           J(25,ij,ik) = JAVAER(79,ij,ik) 
           J(26,ij,ik) = JAVAER(24,ij,ik) 
           J(27,ij,ik) = JAVAER(37,ij,ik) 
           J(28,ij,ik) = JAVAER(23,ij,ik) 
           J(29,ij,ik) = JAVAER(42,ij,ik) 
           J(30,ij,ik) = JAVAER(46,ij,ik) 
           J(31,ij,ik) = JAVAER(45,ij,ik) 
           J(32,ij,ik) = JAVAER(43,ij,ik) 
           J(33,ij,ik) = JAVAER(44,ij,ik) 
           J(34,ij,ik) = JAVAER(63,ij,ik) 
           J(35,ij,ik) = JAVAER(64,ij,ik) 
           J(36,ij,ik) = JAVAER(41,ij,ik) 
           J(37,ij,ik) = JAVAER(40,ij,ik) 
           J(38,ij,ik) = JAVAER(38,ij,ik) 
           J(39,ij,ik) = JAVAER(47,ij,ik) 
           J(40,ij,ik) = JAVAER(57,ij,ik) 
           J(41,ij,ik) = JAVAER(81,ij,ik) 
           J(42,ij,ik) = JAVAER(32,ij,ik)
           J(43,ij,ik) = JAVAER(98,ij,ik)
           J(44,ij,ik) = JAVAER(20,ij,ik) 
           J(45,ij,ik) = JAVAER(104,ij,ik)
           J(46,ij,ik) = JAVAER(119,ij,ik)
           J(47,ij,ik) = JAVAER(78,ij,ik)  
           J(48,ij,ik) = JAVAER(58,ij,ik) 
           J(49,ij,ik) = JAVAER(61,ij,ik) 
           J(50,ij,ik) = JAVAER(21,ij,ik) 
           J(51,ij,ik) = JAVAER(99,ij,ik)
           J(52,ij,ik) = JAVAER(100,ij,ik)
           J(53,ij,ik) = JAVAER(101,ij,ik)
           J(54,ij,ik) = JAVAER(76,ij,ik) 
           J(55,ij,ik) = JAVAER(102,ij,ik)
           J(56,ij,ik) = JAVAER(103,ij,ik)
           J(57,ij,ik) = JAVAER(39,ij,ik) 
           J(58,ij,ik) = JAVAER(60,ij,ik) 
           J(59,ij,ik) = JAVAER(1+iunjr,ij,ik) 
           J(60,ij,ik) = JAVAER(2+iunjr,ij,ik) 
           J(61,ij,ik) = JAVAER(3+iunjr,ij,ik) 
           J(62,ij,ik) = JAVAER(22,ij,ik) 
           J(63,ij,ik) = 0.0E0                 ! JCH3O2 not used in AER model
           J(64,ij,ik) = JAVAER(62,ij,ik) 
           J(65,ij,ik) = JAVAER(65,ij,ik) 
           J(66,ij,ik) = JAVAER(66,ij,ik) 
           J(67,ij,ik) = JAVAER(67,ij,ik) 
           J(68,ij,ik) = JAVAER(77,ij,ik) 
           J(69,ij,ik) = JAVAER(96,ij,ik)
           J(70,ij,ik) = JAVAER(97,ij,ik)
C                                              ! HFCs: J71-J78
           J(71,ij,ik) = JAVAER(111,ij,ik)
           J(72,ij,ik) = JAVAER(112,ij,ik)
           J(73,ij,ik) = JAVAER(113,ij,ik)
           J(74,ij,ik) = JAVAER(114,ij,ik)
           J(75,ij,ik) = JAVAER(115,ij,ik)
           J(76,ij,ik) = JAVAER(116,ij,ik)
           J(77,ij,ik) = JAVAER(117,ij,ik)
           J(78,ij,ik) = JAVAER(118,ij,ik)

           J(79,ij,ik) = JAVAER(105,ij,ik)
           J(80,ij,ik) = JAVAER(106,ij,ik)
           J(81,ij,ik) = JAVAER(107,ij,ik)
 100    CONTINUE



C  load in diurnally varying Js JAER(IUNJR+3,IUNTIME,L$,Z$) into JDC(PH$,18,L$,Z$) 

        DO 200 IK=1,Z$
        DO 200 IJ=1,L$
        DO 200 ITT=1,IUNTIME
           JDC(1,itt,ij,ik) = JAER(1,itt,ij,ik) 
           JDC(2,itt,ij,ik) = JAER(3,itt,ij,ik) 
           JDC(3,itt,ij,ik) = JAER(2,itt,ij,ik) 
           JDC(4,itt,ij,ik) = JAER(12,itt,ij,ik) 
           JDC(5,itt,ij,ik) = JAER(7,itt,ij,ik) 
           JDC(6,itt,ij,ik) = JAER(8,itt,ij,ik) 
           JDC(7,itt,ij,ik) = JAER(6,itt,ij,ik) 
           JDC(8,itt,ij,ik) = JAER(11,itt,ij,ik) 
           JDC(9,itt,ij,ik) = JAER(9,itt,ij,ik) 
           JDC(10,itt,ij,ik) = JAER(30,itt,ij,ik) 
           JDC(11,itt,ij,ik) = JAER(31,itt,ij,ik) 
           JDC(12,itt,ij,ik) = JAER(80,itt,ij,ik) 
           JDC(13,itt,ij,ik) = JAER(34,itt,ij,ik) 
           JDC(14,itt,ij,ik) = JAER(13,itt,ij,ik) 
           JDC(15,itt,ij,ik) = JAER(10,itt,ij,ik) 
           JDC(16,itt,ij,ik) = JAER(5,itt,ij,ik) 
           JDC(17,itt,ij,ik) = JAER(59,itt,ij,ik) 
           JDC(18,itt,ij,ik) = JAER(14,itt,ij,ik) 
           JDC(19,itt,ij,ik) = JAER(18,itt,ij,ik) 
           JDC(20,itt,ij,ik) = JAER(19,itt,ij,ik) 
           JDC(21,itt,ij,ik) = JAER(16,itt,ij,ik) 
           JDC(22,itt,ij,ik) = JAER(17,itt,ij,ik) 
           JDC(23,itt,ij,ik) = JAER(15,itt,ij,ik) 
           JDC(24,itt,ij,ik) = JAER(33,itt,ij,ik) 
           JDC(25,itt,ij,ik) = JAER(79,itt,ij,ik) 
           JDC(26,itt,ij,ik) = JAER(24,itt,ij,ik) 
           JDC(27,itt,ij,ik) = JAER(37,itt,ij,ik) 
           JDC(28,itt,ij,ik) = JAER(23,itt,ij,ik) 
           JDC(29,itt,ij,ik) = JAER(42,itt,ij,ik) 
           JDC(30,itt,ij,ik) = JAER(46,itt,ij,ik) 
           JDC(31,itt,ij,ik) = JAER(45,itt,ij,ik) 
           JDC(32,itt,ij,ik) = JAER(43,itt,ij,ik) 
           JDC(33,itt,ij,ik) = JAER(44,itt,ij,ik) 
           JDC(34,itt,ij,ik) = JAER(63,itt,ij,ik) 
           JDC(35,itt,ij,ik) = JAER(64,itt,ij,ik) 
           JDC(36,itt,ij,ik) = JAER(41,itt,ij,ik) 
           JDC(37,itt,ij,ik) = JAER(40,itt,ij,ik) 
           JDC(38,itt,ij,ik) = JAER(38,itt,ij,ik) 
           JDC(39,itt,ij,ik) = JAER(47,itt,ij,ik) 
           JDC(40,itt,ij,ik) = JAER(57,itt,ij,ik) 
           JDC(41,itt,ij,ik) = JAER(81,itt,ij,ik) 
           JDC(42,itt,ij,ik) = JAER(32,itt,ij,ik) 
           JDC(43,itt,ij,ik) = JAER(98,itt,ij,ik)
           JDC(44,itt,ij,ik) = JAER(20,itt,ij,ik) 
           JDC(45,itt,ij,ik) = JAER(104,itt,ij,ik)
           JDC(46,itt,ij,ik) = JAER(119,itt,ij,ik)
           JDC(47,itt,ij,ik) = JAER(78,itt,ij,ik) 
           JDC(48,itt,ij,ik) = JAER(58,itt,ij,ik) 
           JDC(49,itt,ij,ik) = JAER(61,itt,ij,ik) 
           JDC(50,itt,ij,ik) = JAER(21,itt,ij,ik) 
           JDC(51,itt,ij,ik) = JAER(99,itt,ij,ik)
           JDC(52,itt,ij,ik) = JAER(100,itt,ij,ik)
           JDC(53,itt,ij,ik) = JAER(101,itt,ij,ik)
           JDC(54,itt,ij,ik) = JAER(76,itt,ij,ik) 
           JDC(55,itt,ij,ik) = JAER(102,itt,ij,ik)
           JDC(56,itt,ij,ik) = JAER(103,itt,ij,ik)
           JDC(57,itt,ij,ik) = JAER(39,itt,ij,ik) 
           JDC(58,itt,ij,ik) = JAER(60,itt,ij,ik) 
           JDC(59,itt,ij,ik) = JAER(1+iunjr,itt,ij,ik) 
           JDC(60,itt,ij,ik) = JAER(2+iunjr,itt,ij,ik) 
           JDC(61,itt,ij,ik) = JAER(3+iunjr,itt,ij,ik) 
           JDC(62,itt,ij,ik) = JAER(22,itt,ij,ik) 
           JDC(63,itt,ij,ik) = 0.0E0                 ! JCH3O2 not used in AER model
           JDC(64,itt,ij,ik) = JAER(62,itt,ij,ik) 
           JDC(65,itt,ij,ik) = JAER(65,itt,ij,ik) 
           JDC(66,itt,ij,ik) = JAER(66,itt,ij,ik) 
           JDC(67,itt,ij,ik) = JAER(67,itt,ij,ik) 
           JDC(68,itt,ij,ik) = JAER(77,itt,ij,ik) 
           JDC(69,itt,ij,ik) = JAER(96,itt,ij,ik)
           JDC(70,itt,ij,ik) = JAER(97,itt,ij,ik)
C                                                      ! HFCs: J71-J78
           JDC(71,itt,ij,ik) = JAER(111,itt,ij,ik)
           JDC(72,itt,ij,ik) = JAER(112,itt,ij,ik)
           JDC(73,itt,ij,ik) = JAER(113,itt,ij,ik)
           JDC(74,itt,ij,ik) = JAER(114,itt,ij,ik)
           JDC(75,itt,ij,ik) = JAER(115,itt,ij,ik)
           JDC(76,itt,ij,ik) = JAER(116,itt,ij,ik)
           JDC(77,itt,ij,ik) = JAER(117,itt,ij,ik)
           JDC(78,itt,ij,ik) = JAER(118,itt,ij,ik)

           JDC(79,itt,ij,ik) = JAER(105,itt,ij,ik)
           JDC(80,itt,ij,ik) = JAER(106,itt,ij,ik)
           JDC(81,itt,ij,ik) = JAER(107,itt,ij,ik)
 200    CONTINUE

	RETURN
	END
